language: node_js
node_js:
- 9
before_install:
- npm i -g npm@5.6.0
install: npm install
script:
- npm run test
- npm run build:prod
postinstall: npm run build:prod
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: ogvQwj9wKDOAQwOLr5OaXjroN4w1nQDXKf6izGsyPuKmHERovfb/UxplmR1fCd2J2bj+AYJASthWw/JBofz1wMK4qO8obEuz+Cit2m97eNIWZl5b6UvRe3YDwRHwOMT8zF6lTOhuFmHpVMhrxafrXdE56LOn9fgwOXBupiGWaBtTtzflaJGE9rD66gtwwAPeWt6iZKg9kRFkeueJHIRPnl09l2OWEofwRJIkNoInip0UBqaEzVB2xbS0QcFLGwKFt2UZf0gPjhmNKktX4extmmeLUmOgx6epAqbYthFXmxBEmLVuS1MdSR0oqlJ0UsWIyrYR93LMPRak2C/C+wFn+2ZFDCtqzz2czuVK/+RaenEZQWszIuo47LPM5CJENQEeo8SctzKxD2pBhw5uHy5TIxBTUjF0tT+mwWrZqeRJ4XTfcqUuLiVQ63agYaZvSSiFCdrcqEg7m0oBA503PHG/rMabRwduLyizqTkwO4Xj6so8BUem4mqgDz2Ntah52VWSyFCrK8A9i4BalbNigjMhIFnXmUnqYeqTAPHh4YBGd2tIgwCu5UprMaX3edmfj7aP9ppP392aQwK8foPTi6FSJ2lKvR8DJR2O74duRzRV4jeY1mFRxVfNCMHWIiFvPLR6uaqebFLyqmuzlGunhQQ94FkBXPZtXdZBylAhBjbt0d0=
  app:
    develop: kicky-home-staging
    master: kicky-home
  on:
    repo: better-live-movement/kicky-web
# safelist
branches:
  only:
  - master
  - develop
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
